### PR TITLE
Fixed Issue-52 / Implemented Issue15 and Issue-17

### PR DESCRIPTION
**Pull request by aytchell**
## Motivation

There's a bug in StateMachineConfig.disableEntryActionOfInitialState().
In its current form this method enables the entry action instead of
disabling it.
## Modifications

Wrote a (red) unit test to show the wrong behaviour. Replaced 'true'
with 'false'. Unit test turned green.
## Result

StateMachineConfig.disableEntryActionOfInitialState now works correctly
as its name says.

### CODE REVIEW

**Comment by aytchell** [comment]
This pull request fixes #52

**Comment by aytchell** [comment]
Stumbled upon #49 which applies the same fix. I also added a unit test ;-)

**Comment by aytchell** [comment]
I also implemented #17 which built up on the implementation of #15 .
Since the fix for #52 was so tiny I merged them all together into this pull request.

**Comment by Ktar5** [comment]
Just wanted to give a huge thank you for this amazing pull request.

**Pull request merged**
